name = "Ferret"
grammar = "ferret"
path_suffixes = ["fer"]
line_comments = ["// "]
block_comments = [["/*", "*/"]]
icon = "ferret.png"
tab_size = 4
hard_tabs = false

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
